name: Product Deploy

on:
  push:
    branches:
      - main

jobs:
  product-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Загрузка репозитория
        uses: actions/checkout@v2
      - name: Установка настроек окружения
        run: |
          echo "${{ secrets.DEPLOY_ENV }}" > ".env"
      - name: Развёртывание приложения
        run: |
          eval `ssh-agent -s`
          ssh-add <<< "${{ secrets.DEPLOY_KEY }}"
          export DOCKER_HOST="ssh://deploy@doka.guide"
          docker ps
          docker-compose --project-directory ./ up --force-recreate --detach 
          docker ps
