name: Product Deploy

on:
  push:
    branches:
      - main

jobs:
  product-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Загрузка репозитория
        uses: actions/checkout@v2
      - name: Установка ключа для пользователя
        run: |
          set -eu
          mkdir "$HOME/.ssh"
          echo "${{ secrets.DEPLOY_KEY }}" > "$HOME/.ssh/doka_deploy"
          chmod 600 "$HOME/.ssh/doka_deploy"
      - name: Копирование настроек окружения
        run: |
          echo "${{ secrets.DEPLOY_ENV }}" > ".env"
      - name: Развёртывание приложения
        run: |
          eval `ssh-agent -s`
          ssh-add -k "$HOME/.ssh/doka_deploy"
          export DOCKER_HOST="ssh://deploy@doka.guide"
          docker ps
          docker-compose --project-directory ./ up --force-recreate --detach 
          docker ps
