name: Product Deploy

on:
  push:
    branches:
      - main

jobs:
  product-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Загрузка репозитория
        uses: actions/checkout@v2
      - name: Установка ключа для пользователя
        run: |
          set -eu
          mkdir "$HOME/.ssh"
          echo "${{ secrets.DEPLOY_KEY }}" > "$HOME/.ssh/doka_deploy"
          chmod 600 "$HOME/.ssh/doka_deploy"
          eval `ssh-agent -s`
          ssh-add -k "$HOME/.ssh/doka_deploy"
      - name: Копирование настроек окружения
        run: |
          set -eu
          echo "${{ secrets.DEPLOY_ENV }}" > ".env"
      - name: Публикация приложения
        run: |
          rsync --archive --progress --compress --delete . deploy@doka.guide:$(echo $(grep 'SERVER_PATH' .env | cut -d '=' -f2))
      - name: Развёртывание приложения
        run: |
          ssh deploy@doka.guide cd $(echo $(grep 'SERVER_PATH' .env | cut -d '=' -f2)) && docker-compose build api
          ssh deploy@doka.guide cd $(echo $(grep 'SERVER_PATH' .env | cut -d '=' -f2)) && docker-compose up --no-deps --detach -d api