name: Product Deploy

on:
  push:
    branches:
      - main

jobs:
  product-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Загрузка репозитория
        uses: actions/checkout@v2
      - name: Установка ключа для пользователя
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< "${{ secrets.DEPLOY_KEY }}"
      - name: Копирование настроек окружения
        run: |
          echo "${{ secrets.DEPLOY_ENV }}" > ".env"
      - name: Публикация приложения
        run: |
          rsync -e "ssh -o StrictHostKeyChecking=no" --archive --progress --compress --delete . deploy@doka.guide:$(echo $(grep 'SERVER_PATH' .env | cut -d '=' -f2))
      - name: Развёртывание приложения
        run: |
          ssh deploy@doka.guide cd $(echo $(grep 'SERVER_PATH' .env | cut -d '=' -f2)) && docker-compose build api && docker-compose up --no-deps --detach -d api