name: Product Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  product-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Загрузка репозитория
        uses: actions/checkout@v2
      - name: Установка ключа для пользователя
        run: |
          set -eu
          mkdir "$HOME/.ssh"
          chmod 700 "$HOME/.ssh"
          echo "${{ secrets.DEPLOY_KEY }}" > "$HOME/.ssh/id_rsa"
          chmod 600 "$HOME/.ssh/id_rsa"
      - name: Копирование настроек окружения
        run: |
          echo "${{ secrets.DEPLOY_ENV }}" > ".env"
      - name: Развёртывание приложения
        run: |
          CONTENT_PATH="/web/sites/api.doka.guide/www"
          ssh-keyscan -H doka.guide >> ~/.ssh/known_hosts
          export DOCKER_HOST="ssh://deploy@dev.doka.guide"
          docker stop api
          docker image rm api
          docker build -t api .
          docker run -dti --rm -p "$PORT":"$PORT" --name api --mount type=bind,source="$CONTENT_PATH",target=/app/api api
